# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go handle commit to main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v -o ./build/ .

    - name: Build bundle
      run: cp -r templates build && cd build && tar -czvf dumbproxy-log-monitor.tar.gz .

    - name: See files
      run: tar -tf build/dumbproxy-log-monitor.tar.gz
